
name: Scan secrets Trufflehog

on: push

jobs:
  ScanSecrets:
    name: Scan secrets
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up TruffleHog
          run: |
            docker pull trufflesecurity/trufflehog:latest
        - name: Run TruffleHog
          id: trufflehog
          run: |
              docker run --rm -v $PWD:/pwd trufflesecurity/trufflehog:latest github --repo https://github.com/lucastrogo/TaskGuard --exclude-paths=/pwd/trufflehog-exclude-path.txt
